### ISSUE TITLE
Лаб 3

### ISSUE THREAD

**Issue by lasbio** [samaletwf/Database_labs#1]
1. Нет комментариев
2. task2 - timetemp - LIKE.
3. task4 - сортировка отличается от заданной в задании.
4.  task5 - в условиях задания нет ограничений на гостей и "tennis", зато есть ограничения на номера кортов.
5. task6  - зачем условия на CASE в WHERE, разве нельзя указать условия впрямую?
6. task7  - не верно.

**Comment by samaletwf** [comment]
все ошибки исправил

**Comment by lasbio** [comment]
4 - сортировка
5 - не верно
7 - не верно
